-- Reconstructed Luau source (luauc64 0.1.0).
-- This is a best-effort lift from bytecode; review before running.

CreditsScreen = {TITLE = 0, TEXT = 1, SEPARATOR = 2, DISCLAIMER = 3, CONTROLS = {"achievementsButton", CREDITS_TITLE_ELEMENT = "creditsTitleElement", CREDITS_TEXT_ELEMENT = "creditsTextElement", CREDITS_DISCLAIMER_ELEMENT = "creditsDisclaimerElement", CREDITS_BOX = "creditsVisibilityBox", CREDITS_PLACEHOLDER = "creditsPlaceholder", LOGO = "logo", SIDEBAR = "sidebar", FULL_BG = "fullBg", MAIN_CONTAINER = "mainContainer", BUTTON_BOX = "buttonBox", CHANGE_LANGUAGE_BUTTON = "changeLanguageButton"}, LIST_TEMPLATE_ELEMENT_NAME = {}}
local CreditsScreen_mt = Class(CreditsScreen, ScreenElement)
function CreditsScreen.register()
  local v0 = CreditsScreen.new()
  v1:loadGui("dataS/gui/CreditsScreen.xml", "CreditsScreen", v0)
end
function CreditsScreen.new(target, custom_mt)
  if not custom_mt then
  end
  local v2 = v2(v3, v4)
  v2:registerControls(CreditsScreen.CONTROLS)
  v2.returnScreenName = "MainScreen"
  return v2
end
function CreditsScreen:createFromExistingGui(v1)
  local v2 = CreditsScreen.new()
  v3:delete()
  v3:delete()
  v3:loadGui(self.xmlFilename, v1, v2)
  return v2
end
function CreditsScreen:onCreate(element)
  v2:unlinkElement()
  v2:unlinkElement()
  v2:unlinkElement()
  self:loadCredits()
  self.creditsStartY = self.creditsPlaceholder.absPosition[2]
end
function CreditsScreen:onOpen()
  local v2 = v2:superClass()
  v2.onOpen(self)
  if Platform.isMobile then
    self.mainContainer.absSize[1] = (g_screenWidth - self.sidebar.absSize[1] * g_screenWidth - 50) / g_screenWidth
    v2:setAnchors(0, 1 - (g_screenWidth - self.sidebar.absSize[1] * g_screenWidth - 50) / g_screenWidth - self.creditsVisibilityBox.size[1], 0.1, 0.9)
    self.mainContainer.absPosition[1] = 1 - (g_screenWidth - self.sidebar.absSize[1] * g_screenWidth - 50) / g_screenWidth
    v2:setAnchors(self.mainContainer.absPosition[1], 1, 0, 1)
    v2:updateAbsolutePosition()
    v2 = getPlatformId()
    if v2 == PlatformId.ANDROID then
      local v5 = getIsUserSignedIn()
      v2:setDisabled(not v5)
    end
  end
  if Platform.hasMainScreenLanguageSelection then
    v1:setVisible(true)
    v1:invalidateLayout()
  end
  for v4, v5 in pairs(self.creditsElements) do
    v5:setAlpha(0)
  end
  self.nextFadeInCreditsItemId = 1
  self.nextFadeOutCreditsItemId = 1
  v1:setAbsolutePosition(self.creditsPlaceholder.absPosition[1], self.creditsStartY)
  self:updateTheme()
end
function CreditsScreen:delete()
  v1:delete()
  v1:delete()
  v1:delete()
  local v2 = v2:superClass()
  v2.delete(self)
end
function CreditsScreen:update(dt)
  local v3 = v3:superClass()
  v3.update(self, dt)
  v2:setAbsolutePosition(self.creditsPlaceholder.absPosition[1], self.creditsPlaceholder.absPosition[2] + 0.00007 * dt)
  if self.nextFadeInCreditsItemId <= #self.creditsElements and self.creditsVisibilityBox.absPosition[2] < self.creditsElements[self.nextFadeInCreditsItemId].absPosition[2] then
    v3:fadeIn(1.2)
    self.nextFadeInCreditsItemId = self.nextFadeInCreditsItemId + 1
  end
  if self.nextFadeOutCreditsItemId <= #self.creditsElements then
    -- if v0.creditsVisibilityBox.absPosition[2] + v0.creditsVisibilityBox.absSize[2] * 0.8 >= v0.creditsElements[v0.nextFadeOutCreditsItemId].absPosition[2] then goto L111 end
    v3:fadeOut(4)
    self.nextFadeOutCreditsItemId = self.nextFadeOutCreditsItemId + 1
    return
  end
  self:onClickBack()
end
function CreditsScreen:loadCredits()
  table.insert({}, {t = CreditsScreen.TITLE, c = "Developed by"})
  table.insert({}, {t = CreditsScreen.TEXT, c = "GIANTS Software GmbH"})
  table.insert({}, {t = CreditsScreen.SEPARATOR})
  table.insert({}, {t = CreditsScreen.TITLE, c = "Executive Producer"})
  table.insert({}, {t = CreditsScreen.TEXT, c = "Christian Ammann"})
  table.insert({}, {t = CreditsScreen.SEPARATOR})
  table.insert({}, {t = CreditsScreen.TITLE, c = "Chief Technical Officer"})
  table.insert({}, {t = CreditsScreen.TEXT, c = "Stefan Geiger"})
  table.insert({}, {t = CreditsScreen.SEPARATOR})
  table.insert({}, {t = CreditsScreen.TITLE, c = "Creative Director"})
  table.insert({}, {t = CreditsScreen.TEXT, c = "Thomas Frey"})
  table.insert({}, {t = CreditsScreen.SEPARATOR})
  table.insert({}, {t = CreditsScreen.TITLE, c = "Lead Level Designer"})
  table.insert({}, {t = CreditsScreen.TEXT, c = "Renzo Thönen"})
  table.insert({}, {t = CreditsScreen.SEPARATOR})
  table.insert({}, {t = CreditsScreen.TITLE, c = "Lead Programmer"})
  table.insert({}, {t = CreditsScreen.TEXT, c = "Thomas Brunner"})
  table.insert({}, {t = CreditsScreen.SEPARATOR})
  table.insert({}, {t = CreditsScreen.TITLE, c = "Lead Gameplay Programmer"})
  table.insert({}, {t = CreditsScreen.TEXT, c = "Manuel Leithner"})
  table.insert({}, {t = CreditsScreen.SEPARATOR})
  table.insert({}, {t = CreditsScreen.TITLE, c = "Lead Artist"})
  table.insert({}, {t = CreditsScreen.TEXT, c = "Marc Schwegler"})
  table.insert({}, {t = CreditsScreen.SEPARATOR})
  table.insert({}, {t = CreditsScreen.TITLE, c = "Studio Manager"})
  table.insert({}, {t = CreditsScreen.TEXT, c = "Lukáš Kuře"})
  table.insert({}, {t = CreditsScreen.SEPARATOR})
  if Platform.isPlaystation then
    table.insert({}, {t = CreditsScreen.TITLE, c = "Senior PlayStation®4/5 Programmer"})
    table.insert({}, {t = CreditsScreen.TEXT, c = "Eddie Edwards"})
    table.insert({}, {t = CreditsScreen.SEPARATOR})
    table.insert({}, {t = CreditsScreen.TITLE, c = "Senior Programmer"})
  else
    table.insert({}, {t = CreditsScreen.TITLE, c = "Senior Programmer"})
    table.insert({}, {t = CreditsScreen.TEXT, c = "Eddie Edwards"})
  end
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Olivier Fouré"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Samo Jordan"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Programmers"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Bao-Anh Dang-Vu"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Bojan Kerec"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Gino van den Bergen"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Jan Dellsperger"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Laura Jenkins"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Lukas Nussbaumer"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Marius Hofmann"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Nicolas Wrobel"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Stefan Maurus"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Travis Gesslein"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Lead Vehicle Artist"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Tomáš Dostál"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Lead Character Artists"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Roman Pelypenko"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Technical Artists"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Evgeniy Zaitsev"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Horia Serban"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Marta Stolarz"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Artists"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Adii Parab"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Antonio Jose Gonzalez Benitez"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Florian Busse"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Gabriel Hubli"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Ilya Klishin"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Ivan Stanchev"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Jakub Haltmar"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Jakub Havel"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Jakub Valehrach"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Jan Dobrovolný"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Jan Egon Preiss"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Ján Ohajský"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Jozef Rolincin"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Kamil Tesař"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Kevin Ellersiek"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Maksim Povstugar"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Maria Panfilova"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Matěj Ondráček"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Miroslav Halfar"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Maximilian Frömter"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Natalia Tkach"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Radek Švec"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Raul Arencibia"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Reinaldo Artidiello"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Richard Vavruša"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Sergio Poderoso"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Siddhant Patni"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Štěpán Bařina"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Tomáš Bujňák"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Thomas Flachs"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Vilen Saatsazov"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Vladimir Silkin"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Vladyslav Vershytskyi"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Vehicle Integration"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Christian Wachter"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Daniel Witzel"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Niklas Schumacher"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Simon Nussel"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Stephan Bongartz"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Lead Graphic Designer"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Sandra Meier"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Graphic Designers"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Katrin Huber"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Michael Karg"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Lead Audio Designer"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Kristian Caprani"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Audio Designers"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Nils Heine"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "QA Lead"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Martin Schücker"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "QA Analysts"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Adrien Brüllmann"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Benjamin Neußinger"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Jana Stephan"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Loïck Ruß"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Marcel Renke"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Mario Vortkamp"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Head of Publishing"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Boris Stefan"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Head of Marketing & PR"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Martin Rabl"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "PR & Marketing Managers"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Dennis Reisdorf"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Wolfgang Ebert"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Lukas Schreiner"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Release Manager"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Carlo Sarti"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Release Coordinator"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Kenneth Burgess"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Distribution Operations Manager"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Anna Ruß"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Account Manager"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Martin Seidel"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Technical Projects Coordinator"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Jan-Hendrik Pfitzner"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Community Managers"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Christoph Stumpfer"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Kermit Ball"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Lars Malcharek"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Customer Support Lead"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Christofer Zoltan"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Customer Support Representatives"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Detlef Bövers"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Nicholas Frazier"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Web Developers"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Fabian Seitz"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Marten Boessenkool"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Rene Reisenweber"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Lead Video Artist"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Michael Schraut"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Video Artist"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Marco Riccardi"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Timon Chevalier"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Event Manager"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Claas Eilermann"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Jenny Wirsing"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "HR Representative"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Petra Erlbacher"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Office Managers"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Adéla Štrajtová"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Chodon Fürer-Rikyog"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Verena Pappenheimer"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Radio & Music"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Audio Network GmbH"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Music Producer"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Daniel Hren"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "External QA"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Testronic"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Chief Service Officer"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Erik Hittenhausen"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Director of QA"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Adam Biwojno"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Director of Localisation QA"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Gaëlle Caballero"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Functionality QA"})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "QA Project Manager"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Sebastian “Pablot” Kurek"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "QA Lead"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Tomasz Lewandowski"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Associate QA Leads"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Anna Dąbrowska"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Dawid Szeliga"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Maria Koc"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Functionality QA Technicians"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Kacper Szczytowski"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Krzysztof Sowa"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Łukasz Miecznikowski"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Maciej Powała"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Maciej Stępień"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Magdalena Bednarska"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Michał Pielech"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Natalia Krzewińska"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Paweł Pielech"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Shoakhmad Nazarov"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Compliance QA"})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Technical QA Manager"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Paweł “Piekarz” Kołnierzak"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Technical Department Manager"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Iwona Szarzyńska"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Senior Technical Project Lead"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Małgorzata Twarogal"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Technical Project Lead"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Michał “Bobson” Radłowski"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Senior Technical QA Analysts"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Adrian “Dorian” Strzelecki"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Dorian “Tradey” Geisler"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Technical QA Analysts"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Adam Marczak"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Jakub Neyman"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Justyna Fundowicz"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Krzysztof Skóra"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Compliance QA Technicians"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Agata Dylak"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Aneta Majek"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Jakub Babula"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Katarzyna Kalbarczyk"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Łukasz Korolkiewicz"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Compatibility QA"})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Technical QA Manager"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Paweł “Piekarz” Kołnierzak"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Technical Department Manager"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Iwona Szarzyńska"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Associate Technical QA Leads"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Alan Parsons"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Michał Soral"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Compatibility QA Technicians"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Bartłomiej “Akur” Stajkowski"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Dorian “Tradey” Geisler"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Łukasz Sobolewski"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Paweł Kandyba"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Localisation QA"})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Senior Localisation QA Manager"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Valentina Mollica"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Localisation QA Manager"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Jouhaina Ramy"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Localisation QA Project Manager"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Krzysztof Orlikowski"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Localisation QA Lead"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Jamie Kelly-Warwick"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Senior Localisation QA Technicians"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Anthony Brian Yuen"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Charlotte Cameron"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Dennis Born"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Jefta de Cock"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Keiko Naito"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Morten Østergaard"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Piotr Rokitnicki"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Localisation QA Technicians"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Álvaro Saavedra Jeno"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Brice José Fajardo Ory"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Cristina Baleanu"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Davide Fanni"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Jaehun Bae"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Kan Cheng"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Katarzyna Maciejewska"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Marcela Ostrochovska"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Marilia Stieven Sonza"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Pál Veres Kovács"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Roksolana Krushenytska"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Stephen Bubenheim"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  if not Platform.isStadia then
    if Platform.isPC then
      -- cmp-jump LOP_JUMPXEQKS R2 aux=0x101 -> L4885
      -- cmp-jump LOP_JUMPXEQKS R2 aux=0x102 -> L4885
      -- cmp-jump LOP_JUMPXEQKS R2 aux=0x103 -> L4885
      -- cmp-jump LOP_JUMPXEQKS R2 aux=0x104 -> L4885
      -- cmp-jump LOP_JUMPXEQKS R2 aux=0x105 -> L4885
    end
    if Platform.territory == "jp" then
      table.insert(v1, {t = CreditsScreen.SEPARATOR})
      table.insert(v1, {t = CreditsScreen.TITLE, c = "Licensed to and published in Japan by "})
      table.insert(v1, {t = CreditsScreen.TEXT, c = "Bandai Namco Entertainment Inc."})
      table.insert(v1, {t = CreditsScreen.SEPARATOR})
    end
  end
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = ""})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = ""})
  local v9 = v9:getText("ui_copyrightSymbol")
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "Copyright " .. v9 .. " 2003-2023 GIANTS Software GmbH"})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "Farming Simulator"})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "GIANTS Software and its logos are trademarks"})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "or registered trademarks of GIANTS Software"})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "All rights reserved."})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = ""})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "All manufacturers, agricultural machinery,"})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "agricultural equipment, names, brands and"})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "associated imagery featured in this game"})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "in some cases include trademarks and/or"})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "copyrighted materials of their"})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "respective owners. The agricultural"})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "machines and equipment in this game"})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "may be different from the actual machines"})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "in shapes, colours and performance."})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = ""})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "The VOLVO trademarks (word and device),"})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "other related trademarks, if applicable, "})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "and the Volvo designs are licensed by"})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "the AB Volvo Group."})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = ""})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  if not GS_PLATFORM_XBOX and not GS_IS_MOBILE_VERSION then
    local v8 = v8:getText("ui_copyrightSymbol")
    table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = v8 .. " 2023 Sony Interactive Entertainment LLC."})
    table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "\"PlayStation Family Mark\", \"PlayStation\","})
    table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "\"PS5 logo\", \"PS5\", \"PS4 logo\", \"PS4\","})
    table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "\"PlayStation Shapes Logo\" and \"Play Has No Limits\""})
    table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "are registered trademarks or trademarks of"})
    table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "Sony Interactive Entertainment Inc."})
    table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = ""})
  end
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "Uses Lua"})
  v9 = v9:getText("ui_copyrightSymbol")
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "Copyright " .. v9 .. " 1994-2023 Lua.org, PUC-Rio"})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = ""})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  if Platform.Mobile then
    table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "Uses Luau"})
    v9 = v9:getText("ui_copyrightSymbol")
    table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "Copyright " .. v9 .. " 2019-2023 Roblox Corporation"})
    table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = ""})
    table.insert(v1, {t = CreditsScreen.SEPARATOR})
  else
    table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "Uses LuaJIT"})
    v9 = v9:getText("ui_copyrightSymbol")
    table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "Copyright " .. v9 .. " 2005-2023 Mike Pall"})
    table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = ""})
    table.insert(v1, {t = CreditsScreen.SEPARATOR})
  end
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "Uses Ogg Vorbis"})
  v9 = v9:getText("ui_copyrightSymbol")
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "Copyright " .. v9 .. " 1994-2023 Xiph.Org Foundation"})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = ""})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "Uses Zlib"})
  v9 = v9:getText("ui_copyrightSymbol")
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "Copyright " .. v9 .. " 1995-2023 Jean-loup Gailly"})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "and Mark Adler"})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = ""})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "This software is based in part on"})
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "the work of the Independent JPEG Group"})
  v9 = v9:getText("ui_copyrightSymbol")
  table.insert(v1, {t = CreditsScreen.DISCLAIMER, c = "Copyright " .. v9 .. " 1991-2023 Independent JPEG Group"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = "Special Thanks to"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Martin Bärwolf"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Mike Pall"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Andrés Villegas"})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Brian Burgess"})
  table.insert(v1, {t = CreditsScreen.SEPARATOR})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TEXT, c = "Thanks for playing!"})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  table.insert(v1, {t = CreditsScreen.TITLE, c = ""})
  -- TODO: structure LOP_FORNPREP (pc 6460, target 6470)
  v5:delete()
  -- TODO: structure LOP_FORNLOOP (pc 6469, target 6461)
  self.creditsElements = {}
  for v5, v6 in pairs(v1) do
    self.currentCreditsText = v6.c
    if v6.t == CreditsScreen.TITLE then
      v8 = v8:clone(self.creditsPlaceholder)
      v8:updateSize()
      v8:setText(v6.c)
    elseif v6.t == CreditsScreen.TEXT then
      v8 = v8:clone(self.creditsPlaceholder)
      v8:setText(v6.c)
    else
      if v6.t == CreditsScreen.DISCLAIMER then
        v8 = v8:clone(self.creditsPlaceholder)
        v8:setText(v6.c)
      end
    end
    if not (v7 ~= nil) then
      continue
    end
    v7:setAlpha(0)
    table.insert(self.creditsElements, v7)
  end
  v2 = v2:invalidateLayout(true)
  self.creditsEndY = self.creditsPlaceholder.size[2] + v2
end
function CreditsScreen:updateTheme()
  if Platform.gameLogos[g_languageShort] == nil then
  end
  if self.logo ~= nil then
    v2:setImageFilename(v1)
  end
end
function CreditsScreen:onCareerClick(element)
  self:changeScreen(MainScreen)
  v2:setFocus(g_mainScreen.careerButton)
  v2:onCareerClick(element)
end
function CreditsScreen:onAchievementsClick(element)
  self:changeScreen(MainScreen)
  v2:setFocus(g_mainScreen.achievementsButton)
  v2:onAchievementsClick(element)
end
function CreditsScreen.onChangeMobileSettingsClick(v0, v1)
  v2:onChangeMobileSettingsClick(v1)
end
