// Ghidra Decompiler Output - AArch64 (64-bit)
// Function: FUN_00b2b588
// Entry Point: 00b2b588
// Size: 8 bytes
// Signature: undefined FUN_00b2b588(void)


void FUN_00b2b588(__tree<std::__ndk1::__value_type<Resource*,std::__ndk1::vector<std::__ndk1::__map_iterator<std::__ndk1::__tree_iterator<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,std::__ndk1::__tree_node<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,void*>*,long>>,std::__ndk1::allocator<std::__ndk1::__map_iterator<std::__ndk1::__tree_iterator<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,std::__ndk1::__tree_node<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,void*>*,long>>>>>,std::__ndk1::__map_value_compare<Resource*,std::__ndk1::__value_type<Resource*,std::__ndk1::vector<std::__ndk1::__map_iterator<std::__ndk1::__tree_iterator<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,std::__ndk1::__tree_node<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,void*>*,long>>,std::__ndk1::allocator<std::__ndk1::__map_iterator<std::__ndk1::__tree_iterator<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,std::__ndk1::__tree_node<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,void*>*,long>>>>>,std::__ndk1::less<Resource*>,true>,std::__ndk1::allocator<std::__ndk1::__value_type<Resource*,std::__ndk1::vector<std::__ndk1::__map_iterator<std::__ndk1::__tree_iterator<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,std::__ndk1::__tree_node<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,void*>*,long>>,std::__ndk1::allocator<std::__ndk1::__map_iterator<std::__ndk1::__tree_iterator<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,std::__ndk1::__tree_node<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,void*>*,long>>>>>>>
                  *param_1)

{
  std::__ndk1::
  __tree<std::__ndk1::__value_type<Resource*,std::__ndk1::vector<std::__ndk1::__map_iterator<std::__ndk1::__tree_iterator<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,std::__ndk1::__tree_node<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,void*>*,long>>,std::__ndk1::allocator<std::__ndk1::__map_iterator<std::__ndk1::__tree_iterator<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,std::__ndk1::__tree_node<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,void*>*,long>>>>>,std::__ndk1::__map_value_compare<Resource*,std::__ndk1::__value_type<Resource*,std::__ndk1::vector<std::__ndk1::__map_iterator<std::__ndk1::__tree_iterator<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,std::__ndk1::__tree_node<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,void*>*,long>>,std::__ndk1::allocator<std::__ndk1::__map_iterator<std::__ndk1::__tree_iterator<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,std::__ndk1::__tree_node<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,void*>*,long>>>>>,std::__ndk1::less<Resource*>,true>,std::__ndk1::allocator<std::__ndk1::__value_type<Resource*,std::__ndk1::vector<std::__ndk1::__map_iterator<std::__ndk1::__tree_iterator<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,std::__ndk1::__tree_node<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,void*>*,long>>,std::__ndk1::allocator<std::__ndk1::__map_iterator<std::__ndk1::__tree_iterator<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,std::__ndk1::__tree_node<std::__ndk1::__value_type<ResourceManager::InternalResourceDesc,Resource*>,void*>*,long>>>>>>>
  ::destroy(param_1,*(__tree_node **)(param_1 + 8));
  return;
}


