// Ghidra Decompiler Output - AArch64 (64-bit)
// Function: init
// Entry Point: 006e2d84
// Size: 7352 bytes
// Signature: undefined __cdecl init(EngineApplication * param_1)


/* GameScriptBinding::init(EngineApplication*) */

void GameScriptBinding::init(EngineApplication *param_1)

{
  LuauScriptSystem *pLVar1;
  
  s_pApplication = param_1;
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4a3c,"source");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4a58,"usleep");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4a74,"setCurrentProcessPriority");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4a90,"setLanguage");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4aac,"getNumOfScreenModes");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4ac8,"getScreenModeInfo");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4ae4,"getScreenMode");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4b00,"setScreenMode");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4b1c,"getResolutionScaling");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4b38,"setResolutionScaling");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4b54,"getUiResolutionScaling");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4b70,"setUiResolutionScaling");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4b8c,"get3dResolutionScaling");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4ba8,"set3dResolutionScaling");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4bc4,"getSafeFrameInsets");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4be0,"getScreenHdrOutput");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4bfc,"setScreenHdrOutput");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4c18,"executeSettingsChange");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4c34,"getScreenAspectRatio");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4c50,"promptUserConfirmScreenMode");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4c6c,"setUserConfirmScreenMode");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4c88,"getStartMode");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4ca4,"setStartMode");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4cc0,"getFullscreenMode");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4cdc,"setFullscreenMode");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClass
            (pLVar1,"FullscreenMode",(char *)0x0,(_func_int_void_ptr *)0x0,(_func_int_void_ptr *)0x0
            );
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::beginClass(pLVar1,"FullscreenMode");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0,"WINDOWED");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,1,"WINDOWED_FULLSCREEN");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,2,"EXCLUSIVE_FULLSCREEN");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,3,"NUM");
  ScriptSystemManager::getInstance();
  ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::endClass();
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4cf8,"getVsync");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4d14,"setVsync");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4d30,"getAdaptiveVsync");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4d4c,"setAdaptiveVsync");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4d68,"getBrightness");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4d84,"setBrightness");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4da0,"getBrightnessNits");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4dbc,"setBrightnessNits");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4dd8,"updateLoadingBar");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4df4,"toggleShowFPS");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4e10,"toggleStatsOverlay");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4e2c,"printStatsOverlay");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4e48,"setFileLogPrefixTimestamp");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4e64,"printActiveEntities");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4e80,"executeConsoleCommand");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4e9c,"setFramerateLimiter");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4eb8,"getGamepadEnabled");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4ed4,"setGamepadEnabled");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4ef0,"getGamepadVibrationEnabled");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4f0c,"setGamepadVibrationEnabled");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4f28,"getGamepadDefaultDeadzone");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4f44,"setGamepadDefaultDeadzone");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4f60,"beginInputFuzzing");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4f7c,"getKeyName");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4f98,"getMouseButtonName");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4fb4,"enableDevelopmentControls");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4fd0,"getMasterVolume");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e4fec,"setMasterVolume");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5008,"getCurrentMasterVolume");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5024,"setCurrentMasterVolume");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5040,"setTerrainLoadDirectory");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClass
            (pLVar1,"TerrainLoadFlags",(char *)0x0,(_func_int_void_ptr *)0x0,
             (_func_int_void_ptr *)0x0);
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::beginClass(pLVar1,"TerrainLoadFlags");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,1,"TEXTURE_CACHE");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,2,"LOD_TEXTURE_CACHE");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,4,"NORMAL_MAP_CACHE");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,8,"OCCLUDER_CACHE");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0x10,"DENSITY_MAPS_USE_LOAD_DIR");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0x40,"TEXTURE_CACHE_USE_LOAD_DIR");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0x20,"HEIGHT_MAP_USE_LOAD_DIR");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0x80,"NORMAL_MAP_CACHE_USE_LOAD_DIR");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0x100,"OCCLUDER_CACHE_USE_LOAD_DIR");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0x1ff,"GAME_DEFAULT");
  ScriptSystemManager::getInstance();
  ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::endClass();
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e505c,"setStereoRendering");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5078,"setInvertStereoRendering");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5094,"restartApplication");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e50b0,"requestExit");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e50cc,"enterCpuBoostMode");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e50e8,"leaveCpuBoostMode");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5104,"wrapMousePosition");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5120,"setShowMouseCursor");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e513c,"requestGamepadSignin");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5158,"isGamepadSigninPending");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5174,"getNumOfGamepads");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5190,"getGamepadName");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e51ac,"getGamepadId");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e51c8,"getHasGamepadAxis");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e51e4,"getHasGamepadButton");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5200,"getHasGamepadAxisForceFeedback");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e521c,"getInputAxis");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5238,"getInputButton");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5254,"getIsGamepadMappingReliable");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5270,"getGamepadButtonLabel");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e528c,"getGamepadAxisLabel");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e52a8,"getGamepadAxisPhysicalName");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e52c4,"getGamepadButtonPhysicalName");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e52e0,"getGamepadMappedUnknownAxis");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e52fc,"getGamepadMappedUnknownButton");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5318,"setGamepadAxisForceFeedback");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5334,"getGamepadVendorId");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5350,"getGamepadProductId");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e536c,"getGamepadVersionId");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5388,"setGamepadVibration");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e53a4,"setGamepadDeadzone");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e53c0,"setGamepadDigitalOutput");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e53dc,"getGravityDirection");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e53f8,"getHasTouchpad");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5414,"getIsKeyboardAvailable");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5430,"isHeadTrackingAvailable");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e544c,"getHeadTrackingType");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5468,"getHeadTrackingTranslation");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5484,"getHeadTrackingRotation");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e54a0,"centerHeadTracking");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e54bc,"setCameraTrackingSensitivity");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e54d8,"getCameraTrackingSensitivity");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e54f4,"setBeaconLights");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5510,"getNumOfBeaconLights");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e552c,"setCaption");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5548,"getAppBasePath");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5564,"getUserProfileAppPath");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5580,"getIsBadUserReputation");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e559c,"getNumDlcPaths");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e55b8,"getDlcPath");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e55d4,"deleteFolder");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e55f0,"getProcessorName");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e560c,"getProcessorFrequency");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5628,"getNumOfProcessors");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5644,"getRenderDriver");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5660,"getGPUName");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e567c,"getGPUVendor");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5698,"getGPUDriverVersion");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e56b4,"getOSVersionName");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e56d0,"getTotalSystemMemory");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e56ec,"getUserName");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5708,"getUserId");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5724,"getUniqueUserId");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5740,"addConsoleCommand");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e575c,"removeConsoleCommand");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5778,"removeActivation");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5794,"storeHaveDlcsChanged");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e57b0,"storeAreDlcsCorrupted");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e57cc,"storeHasNativeGUI");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e57e8,"storeGetOnlineState");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5804,"storeBeginUserSignIn");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5820,"storeGetNumProducts");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e583c,"storeGetProductInfo");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5858,"storeGetProductPrice");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5874,"storeOpenBuyPage");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5890,"storeGetBuyPageState");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e58ac,"storeRequestCloseBuyPage");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClass
            (pLVar1,"Store",(char *)0x0,(_func_int_void_ptr *)0x0,(_func_int_void_ptr *)0x0);
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::beginClass(pLVar1,"Store");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0,"STORE_NONE");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,1,"STORE_CLOSED");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,2,"STORE_ACTIVE");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,3,"STORE_COMPLETE");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,4,"STORE_ABORT");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,5,"STORE_ERROR");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0,"STORE_OFFLINE");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,1,"STORE_GOING_ONLINE");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,2,"STORE_ONLINE");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,3,"STORE_NETFAIL");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,4,"STORE_AGE_RESTRICTED");
  ScriptSystemManager::getInstance();
  ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::endClass();
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e58c8,"showUserProfile");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e58e4,"reportUser");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClass
            (pLVar1,"ReportUserReason",(char *)0x0,(_func_int_void_ptr *)0x0,
             (_func_int_void_ptr *)0x0);
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::beginClass(pLVar1,"ReportUserReason");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0,"PLAYER_NAME");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,1,"VOICE_CHAT");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,2,"TEXT_CHAT");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,3,"BEHAVIOR");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,4,"CHEATING");
  ScriptSystemManager::getInstance();
  ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::endClass();
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5900,"adsAddOcclusionRegion");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e591c,"adsGetOcclusionRegion");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5938,"adsClearOcclusionRegionGroup");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5954,"adsSetIsOcclusionRegionGroupActive");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5970,"adsGetIsOcclusionRegionGroupActive");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e598c,"masterServerInit");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e59a8,"masterServerSetCallbacks");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e59c4,"masterServerRequestConnectionToServer");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e59e0,"masterServerConnectFront");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e59fc,"masterServerConnectBack");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5a18,"masterServerDisconnect");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5a34,"masterServerReconnect");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5a50,"masterServerAddAvailableModStart");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5a6c,"masterServerAddAvailableMod");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5a88,"masterServerAddAvailableModEnd");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5aa4,"masterServerAddDlcStart");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5ac0,"masterServerAddDlc");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5adc,"masterServerAddDlcEnd");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5af8,"masterServerRequestFilteredServers");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5b14,"masterServerRequestServerDetails");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod
            (pLVar1,FUN_006e5b30,"masterServerRequestServerDetailsWithPlatformServerId");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5b4c,"masterServerGetServerUserInfo");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5b68,"masterServerAddServerModStart");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5b84,"masterServerAddServerMod");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5ba0,"masterServerAddServerModEnd");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5bbc,"masterServerAddServer");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5bd8,"masterServerSetServerNumPlayers");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5bf4,"masterServerSetServerInfo");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5c10,"masterServerSetServerPlatformSessionIds");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5c2c,"getNATType");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClass
            (pLVar1,"NATType",(char *)0x0,(_func_int_void_ptr *)0x0,(_func_int_void_ptr *)0x0);
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::beginClass(pLVar1,"NATType");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0,"NAT_UNKNOWN");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,1,"NAT_OPEN");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,2,"NAT_MODERATE");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,3,"NAT_STRICT");
  ScriptSystemManager::getInstance();
  ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::endClass();
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5c48,"setPresenceMode");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5c64,"startFrameRepeatMode");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5c80,"endFrameRepeatMode");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5c9c,"forceEndFrameRepeatMode");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5cb8,"setWindowFocus");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClass
            (pLVar1,"PresenceModes",(char *)0x0,(_func_int_void_ptr *)0x0,(_func_int_void_ptr *)0x0)
  ;
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::beginClass(pLVar1,"PresenceModes");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0,"PRESENCE_IDLE");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,1,"PRESENCE_CAREER");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,2,"PRESENCE_TUTORIAL");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,3,"PRESENCE_MULTIPLAYER");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,4,"PRESENCE_MULTIPLAYER_ALONE");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,5,"PRESENCE_MULTIPLAYER_CROSSPLAY");
  ScriptSystemManager::getInstance();
  ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::endClass();
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClass
            (pLVar1,"DebugRendering",(char *)0x0,(_func_int_void_ptr *)0x0,(_func_int_void_ptr *)0x0
            );
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::beginClass(pLVar1,"DebugRendering");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0,"NONE");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,1,"ALPHA");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,2,"PARALLAX");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,3,"ALBEDO");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,4,"NORMALS");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,5,"TANGENT_SPACE_NORMALS");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,6,"SMOOTHNESS");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,7,"METALNESS");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,8,"AMBIENT_OCCLUSION");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,9,"BAKED_AMBIENT_OCCLUSION");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,10,"SCREEN_SPACE_AMBIENT_OCCLUSION");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0xb,"SPECULAR_OCCLUSION");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0xc,"DIFFUSE_LIGHTING");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0xd,"SPECULAR_LIGHTING");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0xe,"INDIRECT_LIGHTING");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0xf,"LIGHT_GRID");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0x10,"SHADOW_SPLITS");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0x14,"DEPTH");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0x15,"DEPTH_SCALED");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0x11,"MIP_LEVELS");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0x12,"TRIANGLE_DENSITY");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0x13,"TERRAIN_SLOPES");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0x16,"MOTION_VECTORS");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0x17,"SHADING_RATE");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0x18,"MESH_LOD");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0x19,"CUSTOM1");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0x1a,"CUSTOM2");
  ScriptSystemManager::getInstance();
  ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::endClass();
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5cd4,"getDebugRenderingMode");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5cf0,"setDebugRenderingMode");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClass
            (pLVar1,"GamepadCategories",(char *)0x0,(_func_int_void_ptr *)0x0,
             (_func_int_void_ptr *)0x0);
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::beginClass(pLVar1,"GamepadCategories");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,0,"CATEGORY_UNKNOWN");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,2,"CATEGORY_WHEEL");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,3,"CATEGORY_JOYSTICK");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,1,"CATEGORY_GAMEPAD");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,4,"CATEGORY_FARMWHEEL");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,5,"CATEGORY_FARMSIDEPANEL");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,6,"CATEGORY_FARMWHEEL_HORI");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,7,"CATEGORY_FARMSIDEPANEL_HORI");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addClassAttribute(pLVar1,8,"CATEGORY_FARMJOYSTICK_THRUSTMASTER");
  ScriptSystemManager::getInstance();
  ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::endClass();
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5d0c,"getGamepadCategory");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5d28,"getEngineRevision");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5d44,"getGameRevisionExtraText");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5d60,"getEngineState");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5d7c,"getIsUpdateDownloadFinished");
  ScriptSystemManager::getInstance();
  pLVar1 = (LuauScriptSystem *)ScriptSystemManager::getCurrentScriptSystem();
  LuauScriptSystem::addMethod(pLVar1,FUN_006e5d98,"setCloudAllowMeteredConnection");
  return;
}


