// Ghidra Decompiler Output - AArch64 (64-bit)
// Function: saveImage
// Entry Point: 00a99618
// Size: 972 bytes
// Signature: undefined __cdecl saveImage(char * param_1, ImageDesc * param_2)


/* PNGUtil::saveImage(char const*, ImageDesc const&) */

uint PNGUtil::saveImage(char *param_1,ImageDesc *param_2)

{
  long lVar1;
  uint uVar2;
  int iVar3;
  long *plVar4;
  ulong uVar5;
  long lVar6;
  long lVar7;
  uint uVar8;
  undefined4 uVar9;
  long local_140;
  long local_138;
  undefined4 local_130 [2];
  long *local_128;
  void *local_120;
  undefined4 local_118;
  undefined local_114;
  undefined8 local_110;
  char *pcStack_108;
  char *pcStack_100;
  undefined8 uStack_f8;
  undefined8 local_f0;
  undefined8 uStack_e8;
  undefined8 uStack_e0;
  undefined8 local_d8;
  char *local_d0;
  char *pcStack_c8;
  undefined8 uStack_c0;
  undefined8 uStack_b8;
  undefined8 local_b0;
  undefined8 uStack_a8;
  undefined8 local_a0;
  char *local_98;
  char *local_90;
  undefined8 uStack_88;
  undefined8 uStack_80;
  undefined8 uStack_78;
  undefined8 local_70;
  long local_68;
  
  lVar1 = tpidr_el0;
  uVar2 = 0;
  local_68 = *(long *)(lVar1 + 0x28);
  uVar9 = 0;
  switch(*(undefined4 *)(param_2 + 0x40)) {
  case 1:
    break;
  default:
    goto switchD_00a99674_caseD_2;
  case 3:
    uVar2 = 0;
    uVar9 = 2;
    break;
  case 4:
    uVar9 = 2;
    goto LAB_00a9969c;
  case 5:
    uVar2 = 0;
    uVar9 = 6;
    break;
  case 6:
    uVar9 = 6;
LAB_00a9969c:
    uVar2 = 1;
  }
  if (*(int *)(param_2 + 0x18) == 1) {
    iVar3 = 8;
LAB_00a996c0:
    plVar4 = (long *)FileManager::get((FileManager *)FileManager::s_singletonFileManager,param_1,1,
                                      false);
    if (plVar4 != (long *)0x0) {
      local_130[0] = 0;
      local_120 = (void *)0x0;
      local_128 = plVar4;
      uVar5 = (**(code **)(*plVar4 + 0x60))();
      if ((uVar5 & 1) == 0) {
        local_120 = operator_new__(0x20000);
      }
      local_118 = 0;
      local_114 = 0;
                    /* try { // try from 00a99710 to 00a9979b has its CatchHandler @ 00a99a00 */
      lVar6 = png_create_write_struct_2("1.6.37",0,0,0,0,malloc_fn,free_fn);
      local_138 = lVar6;
      if (lVar6 == 0) {
LAB_00a998a8:
        (**(code **)(*plVar4 + 8))(plVar4);
        uVar2 = 0;
      }
      else {
        lVar7 = png_create_info_struct(lVar6);
        local_140 = lVar7;
        if (lVar7 == 0) {
                    /* try { // try from 00a9989c to 00a998a7 has its CatchHandler @ 00a99a00 */
          png_destroy_write_struct(&local_138,0);
          goto LAB_00a998a8;
        }
        png_set_write_fn(lVar6,local_130,user_write_data,user_flush_data);
        png_set_IHDR(lVar6,lVar7,*(undefined4 *)param_2,*(undefined4 *)(param_2 + 4),iVar3,uVar9,0,0
                     ,0);
        local_70 = 0;
        uStack_f8 = 0;
        pcStack_108 = "Generated by";
        pcStack_100 = "GIANTS";
        uStack_b8 = 0;
        uStack_c0 = 0;
        uStack_88 = 0;
        uStack_78 = 0;
        uStack_80 = 0;
        uStack_a8 = 0;
        local_b0 = 0;
        local_d0 = "Author\'s name";
        pcStack_c8 = "GIANTS Software GmbH";
        uStack_e8 = 0;
        local_f0 = 0;
        uStack_e0 = 0;
        local_110 = 0xffffffff;
        local_d8 = 0xffffffff;
        local_98 = "Author\'s comments";
        local_90 = "GIANTS Engine";
        local_a0 = 0xffffffff;
                    /* try { // try from 00a99804 to 00a99837 has its CatchHandler @ 00a999fc */
        png_set_text(lVar6,lVar7,&local_110,3);
        png_write_info(lVar6,lVar7);
        png_set_swap(lVar6);
        if (uVar2 != 0) {
          png_set_bgr(lVar6);
        }
        uVar2 = (uint)(*(int *)param_2 * iVar3 * *(int *)(param_2 + 0x14)) >> 3;
        if (*(int *)(param_2 + 0x44) == 1) {
          if (*(int *)(param_2 + 4) != 0) {
            uVar5 = 0;
            uVar8 = uVar2 * (*(int *)(param_2 + 4) + -1);
            do {
                    /* try { // try from 00a99874 to 00a9987b has its CatchHandler @ 00a99a08 */
              png_write_row(lVar6,*(long *)(param_2 + 0x28) + (ulong)uVar8);
              uVar5 = uVar5 + 1;
              uVar8 = uVar8 - uVar2;
            } while (uVar5 < *(uint *)(param_2 + 4));
          }
        }
        else if (*(int *)(param_2 + 4) != 0) {
          uVar8 = 0;
          uVar5 = 0;
          do {
                    /* try { // try from 00a99914 to 00a9991b has its CatchHandler @ 00a99a04 */
            png_write_row(lVar6,*(long *)(param_2 + 0x28) + (ulong)uVar8);
            uVar5 = uVar5 + 1;
            uVar8 = uVar8 + uVar2;
          } while (uVar5 < *(uint *)(param_2 + 4));
        }
                    /* try { // try from 00a99930 to 00a9997b has its CatchHandler @ 00a999f8 */
        png_write_end(lVar6,lVar7);
        png_destroy_write_struct(&local_138,&local_140);
        uVar2 = CompressedIoUtil::CompressedFileOutput<unsigned_char>::finishWriting();
        if ((uVar2 & 1) == 0) {
          if (((LogManager::getInstance()::singletonLogManager & 1) == 0) &&
             (iVar3 = __cxa_guard_acquire(&LogManager::getInstance()::singletonLogManager),
             iVar3 != 0)) {
                    /* try { // try from 00a999a8 to 00a999b3 has its CatchHandler @ 00a999e4 */
            LogManager::LogManager((LogManager *)&LogManager::getInstance()::singletonLogManager);
            __cxa_atexit(LogManager::~LogManager,&LogManager::getInstance()::singletonLogManager,
                         &PTR_LOOP_00fd8de0);
            __cxa_guard_release(&LogManager::getInstance()::singletonLogManager);
          }
          LogManager::errorf((char *)&LogManager::getInstance()::singletonLogManager,
                             "PNG write failed\n");
        }
        (**(code **)(*plVar4 + 8))(plVar4);
      }
      if (local_120 != (void *)0x0) {
        operator_delete__(local_120);
      }
      goto switchD_00a99674_caseD_2;
    }
  }
  else if (*(int *)(param_2 + 0x18) == 3) {
    iVar3 = 0x10;
    goto LAB_00a996c0;
  }
  uVar2 = 0;
switchD_00a99674_caseD_2:
  if (*(long *)(lVar1 + 0x28) == local_68) {
    return uVar2 & 1;
  }
                    /* WARNING: Subroutine does not return */
  __stack_chk_fail();
}


