-- Reconstructed Luau source (luauc64 0.1.0).
-- This is a best-effort lift from bytecode; review before running.

BezierTest = {}
function BezierTest.test_constructor()
  Assert.throwsError(BezierCurve.new, "Calling constructor with no arguments threw no error.")
  Assert.throwsError(function()
    BezierCurve.new(nil, 0, 0, 0)
  end, "X 1 was allowed to be invalid")
  Assert.throwsError(function()
    BezierCurve.new(0, nil, 0, 0)
  end, "Y 1 was allowed to be invalid")
  Assert.throwsError(function()
    BezierCurve.new(0, 0, nil, 0)
  end, "X 2 was allowed to be invalid")
  Assert.throwsError(function()
    BezierCurve.new(0, 0, 0, nil)
  end, "Y 2 was allowed to be invalid")
end
function BezierTest.test_setters()
  local v0 = BezierCurve.new(0.25, 0, 0.75, 1)
  Assert.throwsError(function()
    v0:setPositionX1(nil)
  end, "X 1 was allowed to be invalid")
  Assert.throwsError(function()
    v0:setPositionY1(nil)
  end, "Y 1 was allowed to be invalid")
  Assert.throwsError(function()
    v0:setPositionX2(nil)
  end, "X 2 was allowed to be invalid")
  Assert.throwsError(function()
    v0:setPositionY2(nil)
  end, "Y 2 was allowed to be invalid")
end
function BezierTest.test_solvers()
  local v0 = BezierCurve.new(0.25, 0, 0.75, 1)
  Assert.throwsError(function()
    v0:sampleY(nil)
  end, "t was allowed to be invalid")
  Assert.throwsError(function()
    v0:sampleX(nil)
  end, "t was allowed to be invalid")
  Assert.throwsError(function()
    v0:sampleDerivativeX(nil)
  end, "t was allowed to be invalid")
  Assert.throwsError(function()
    v0:solveX(nil)
  end, "t was allowed to be invalid")
  Assert.throwsError(function()
    v0:solveX(0.5, {})
  end, "epsilon was allowed to be invalid")
  Assert.throwsError(function()
    v0:solve(nil)
  end, "t was allowed to be invalid")
  Assert.throwsError(function()
    v0:solve(0.5, {})
  end, "epsilon was allowed to be invalid")
  -- TODO: structure LOP_FORNPREP (pc 52, target 85)
  local v4 = BezierCurve.new(0 / 100, 0, 1 - 0 / 100, 1)
  for v6 = 0, 100 do
    local v7 = v0:solve(v6 / 100)
    Assert.lessThanOrEqualTo(v7, 1, "Value was greater than 1")
    Assert.greaterThanOrEqualTo(v7, 0, "Value was less than 0")
    -- TODO: structure LOP_FORNLOOP (pc 83, target 67)
  end
end
