-- Reconstructed Luau source (luauc64 0.1.0).
-- This is a best-effort lift from bytecode; review before running.

FoliageXmlUtil = {}
function FoliageXmlUtil:printFoliageCtor()
  local v1 = self:getName()
  local v2, v3 = self:getDensityMapInfo()
  local v4 = self:getNumLayers()
  print("Name: " .. v1)
  print("Density Map: BPP " .. v2 .. " TYPE " .. v3)
  print("Num layers: " .. v4)
  -- TODO: structure LOP_FORNPREP (pc 32, target 335)
  local v9 = self:getNameForLayer(1 - 1)
  local v10 = self:getTypeIndexForLayer(1 - 1)
  local v11 = self:getShapeSourceForLayer(1 - 1)
  local v12, v13 = self:getDensityChannelsForLayer(1 - 1)
  local v14 = self:getCellSizeForLayer(1 - 1)
  local v15 = self:getObjectMaskForLayer(1 - 1)
  local v16 = self:getDecalLayerForLayer(1 - 1)
  local v17 = self:getMaxNumStatesForLayer(1 - 1)
  local v18 = self:getNumStatesForLayer(1 - 1)
  print("Layer " .. 1 - 1 .. ":")
  print("  Name: " .. v9)
  print("  Type index: " .. v10)
  local v22 = tostring(v11)
  print("  Shape Source: " .. v22)
  print("  Density map: CH off " .. v12 .. " BPP " .. v13)
  print("  Cell size: " .. v14)
  print("  Object mask: " .. v15)
  print("  Decal layer: " .. v16)
  print("  Max states: " .. v17)
  print("  Num states: " .. v18)
  for v21 = 1, v18 do
    local v23 = self:getNameForState(v8, v21 - 1)
    local v24, v25 = self:getDistanceMapForState(v8, v21 - 1)
    local v26, v27 = self:getWidthAndVarianceForState(v8, v21 - 1)
    local v28, v29 = self:getHeightAndVarianceForState(v8, v21 - 1)
    local v30 = self:getPositionVarianceForState(v8, v21 - 1)
    local v31 = self:getNumShapesForState(v8, v21 - 1)
    local v32 = self:getBlocksPerUnitForState(v8)
    print("  State " .. v21 - 1 .. ":")
    print("    Name: " .. v23)
    print("    Distance map: " .. v24 .. " layer " .. v25)
    print("    Width: " .. v26 .. " var " .. v27)
    print("    Height: " .. v28 .. " var " .. v29)
    print("    Pos var: " .. v30)
    print("    Num shapes: " .. v31)
    print("    Blocks per unit " .. v32)
    for v35 = 1, v31 do
      local v37 = self:getNumLodsForShape(v8, v22, v35 - 1)
      for v40 = 1, v37 do
        local v42 = self:getViewDistanceForLod(v8, v22, v36, v40 - 1)
        local v43 = self:getShapeForLod(v8, v22, v36, v40 - 1)
        local v44 = self:getAtlasSizeForLod(v8, v22, v36, v40 - 1)
        local v45, v46 = self:getAtlasOffsetForLod(v8, v22, v36, v40 - 1)
        local v47, v48, v49, v50 = self:getTexCoordsForLod(v8, v22, v36, v40 - 1)
        print("    Lod " .. v40 - 1)
        local v54 = tostring(v42)
        print("      ViewDistance " .. v54)
        v54 = tostring(v43)
        print("      Shape " .. v54)
        print("      Atlas size: " .. v44)
        print("      Atlas offset: " .. v45 .. " " .. v46)
        print("      Tex coords: " .. v47 .. " " .. v48 .. " " .. v49 .. " " .. v50)
        -- TODO: structure LOP_FORNLOOP (pc 331, target 245)
      end
    end
  end
end
